--- #YAML:1.0
name:                Log-Dispatch-File-Rolling
version:             1.05
abstract:            Object for logging to date/time/pid
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Log::Dispatch:                 2.06
    Log::Log4perl:                 0.32
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - M. Jacob <jacob@j-e-b.net>
