--- #YAML:1.0
name:               Log-Dispatch-File-Rolling
version:            1.06
abstract:           Object for logging to date/time/pid
author:
    - M. Jacob <jacob@j-e-b.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Dispatch:  2.06
    Log::Log4perl:  0.32
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
