# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Dispatch-File-Rolling
version:      1.04
version_from: Rolling.pm
installdirs:  site
requires:
    Log::Dispatch:                 2.06
    Log::Log4perl:                 0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
